2020-06-07 19:57:44.6167|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:17:10.4821|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:25:14.1286|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:26:07.0278|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:28:33.5935|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:31:33.5683|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast/1|action: GetSingle
2020-06-07 21:50:12.9047|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast|action: GetSingle
2020-06-07 22:02:51.6887|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast|action: GetSingle
2020-06-07 22:09:13.0801|1000|INFO|SPAapi.CustomExceptionAttribute|ttt |url: http://localhost/WeatherForecast|action: GetSingle
2020-06-07 22:17:02.7499|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object.
   at SPAapi.ApiResultFilterAttribute.OnResultExecuting(ResultExecutingContext context) in E:\CodeTest\SPAapi\SPAapi\ValidateModelAttribute.cs:line 49
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: http://localhost/WeatherForecast/GetSingle|action: GetSingle
